/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as UHandleRouteImport } from './routes/u.$handle'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminSumanRouteImport } from './routes/admin.suman'
import { Route as AuthenticatedStartupsRouteImport } from './routes/_authenticated/startups'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMentorRouteImport } from './routes/_authenticated/mentor'
import { Route as AuthenticatedLinkedinOptimizerRouteImport } from './routes/_authenticated/linkedin-optimizer'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedInternshipsRouteImport } from './routes/_authenticated/internships'
import { Route as AuthenticatedHackathonsRouteImport } from './routes/_authenticated/hackathons'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedDevprofileRouteImport } from './routes/_authenticated/devprofile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAlumniRouteImport } from './routes/_authenticated/alumni'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedRoomsIndexRouteImport } from './routes/_authenticated/rooms.index'
import { Route as ApiAdminAgentChatRouteImport } from './routes/api/admin/agent-chat'
import { Route as AuthenticatedRoomsSlugRouteImport } from './routes/_authenticated/rooms.$slug'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSumanRoute = AdminSumanRouteImport.update({
  id: '/admin/suman',
  path: '/admin/suman',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStartupsRoute = AuthenticatedStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorRoute = AuthenticatedMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkedinOptimizerRoute =
  AuthenticatedLinkedinOptimizerRouteImport.update({
    id: '/linkedin-optimizer',
    path: '/linkedin-optimizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInternshipsRoute =
  AuthenticatedInternshipsRouteImport.update({
    id: '/internships',
    path: '/internships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHackathonsRoute = AuthenticatedHackathonsRouteImport.update({
  id: '/hackathons',
  path: '/hackathons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevprofileRoute = AuthenticatedDevprofileRouteImport.update({
  id: '/devprofile',
  path: '/devprofile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlumniRoute = AuthenticatedAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRoomsIndexRoute = AuthenticatedRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAdminAgentChatRoute = ApiAdminAgentChatRouteImport.update({
  id: '/api/admin/agent-chat',
  path: '/api/admin/agent-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoomsSlugRoute = AuthenticatedRoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/alumni': typeof AuthenticatedAlumniRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devprofile': typeof AuthenticatedDevprofileRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/hackathons': typeof AuthenticatedHackathonsRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/linkedin-optimizer': typeof AuthenticatedLinkedinOptimizerRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/startups': typeof AuthenticatedStartupsRoute
  '/admin/suman': typeof AdminSumanRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/rooms/$slug': typeof AuthenticatedRoomsSlugRoute
  '/api/admin/agent-chat': typeof ApiAdminAgentChatRoute
  '/rooms/': typeof AuthenticatedRoomsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/alumni': typeof AuthenticatedAlumniRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devprofile': typeof AuthenticatedDevprofileRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/hackathons': typeof AuthenticatedHackathonsRoute
  '/internships': typeof AuthenticatedInternshipsRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/linkedin-optimizer': typeof AuthenticatedLinkedinOptimizerRoute
  '/mentor': typeof AuthenticatedMentorRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/startups': typeof AuthenticatedStartupsRoute
  '/admin/suman': typeof AdminSumanRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/blog': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/rooms/$slug': typeof AuthenticatedRoomsSlugRoute
  '/api/admin/agent-chat': typeof ApiAdminAgentChatRoute
  '/rooms': typeof AuthenticatedRoomsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/disclaimer': typeof DisclaimerRoute
  '/features': typeof FeaturesRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/alumni': typeof AuthenticatedAlumniRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devprofile': typeof AuthenticatedDevprofileRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/hackathons': typeof AuthenticatedHackathonsRoute
  '/_authenticated/internships': typeof AuthenticatedInternshipsRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/linkedin-optimizer': typeof AuthenticatedLinkedinOptimizerRoute
  '/_authenticated/mentor': typeof AuthenticatedMentorRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/startups': typeof AuthenticatedStartupsRoute
  '/admin/suman': typeof AdminSumanRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/rooms/$slug': typeof AuthenticatedRoomsSlugRoute
  '/api/admin/agent-chat': typeof ApiAdminAgentChatRoute
  '/_authenticated/rooms/': typeof AuthenticatedRoomsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/disclaimer'
    | '/features'
    | '/mcp'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/alumni'
    | '/applications'
    | '/dashboard'
    | '/devprofile'
    | '/discover'
    | '/hackathons'
    | '/internships'
    | '/jobs'
    | '/linkedin-optimizer'
    | '/mentor'
    | '/profile'
    | '/projects'
    | '/resume'
    | '/startups'
    | '/admin/suman'
    | '/blog/$slug'
    | '/u/$handle'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/rooms/$slug'
    | '/api/admin/agent-chat'
    | '/rooms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/disclaimer'
    | '/features'
    | '/mcp'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/alumni'
    | '/applications'
    | '/dashboard'
    | '/devprofile'
    | '/discover'
    | '/hackathons'
    | '/internships'
    | '/jobs'
    | '/linkedin-optimizer'
    | '/mentor'
    | '/profile'
    | '/projects'
    | '/resume'
    | '/startups'
    | '/admin/suman'
    | '/blog/$slug'
    | '/u/$handle'
    | '/blog'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/rooms/$slug'
    | '/api/admin/agent-chat'
    | '/rooms'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/disclaimer'
    | '/features'
    | '/mcp'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/alumni'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/devprofile'
    | '/_authenticated/discover'
    | '/_authenticated/hackathons'
    | '/_authenticated/internships'
    | '/_authenticated/jobs'
    | '/_authenticated/linkedin-optimizer'
    | '/_authenticated/mentor'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/resume'
    | '/_authenticated/startups'
    | '/admin/suman'
    | '/blog/$slug'
    | '/u/$handle'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/rooms/$slug'
    | '/api/admin/agent-chat'
    | '/_authenticated/rooms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FeaturesRoute: typeof FeaturesRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminSumanRoute: typeof AdminSumanRoute
  BlogSlugRoute: typeof BlogSlugRoute
  UHandleRoute: typeof UHandleRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAdminAgentChatRoute: typeof ApiAdminAgentChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suman': {
      id: '/admin/suman'
      path: '/admin/suman'
      fullPath: '/admin/suman'
      preLoaderRoute: typeof AdminSumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/startups': {
      id: '/_authenticated/startups'
      path: '/startups'
      fullPath: '/startups'
      preLoaderRoute: typeof AuthenticatedStartupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentor': {
      id: '/_authenticated/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AuthenticatedMentorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/linkedin-optimizer': {
      id: '/_authenticated/linkedin-optimizer'
      path: '/linkedin-optimizer'
      fullPath: '/linkedin-optimizer'
      preLoaderRoute: typeof AuthenticatedLinkedinOptimizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internships': {
      id: '/_authenticated/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof AuthenticatedInternshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hackathons': {
      id: '/_authenticated/hackathons'
      path: '/hackathons'
      fullPath: '/hackathons'
      preLoaderRoute: typeof AuthenticatedHackathonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devprofile': {
      id: '/_authenticated/devprofile'
      path: '/devprofile'
      fullPath: '/devprofile'
      preLoaderRoute: typeof AuthenticatedDevprofileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alumni': {
      id: '/_authenticated/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AuthenticatedAlumniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/': {
      id: '/_authenticated/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AuthenticatedRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/admin/agent-chat': {
      id: '/api/admin/agent-chat'
      path: '/api/admin/agent-chat'
      fullPath: '/api/admin/agent-chat'
      preLoaderRoute: typeof ApiAdminAgentChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rooms/$slug': {
      id: '/_authenticated/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof AuthenticatedRoomsSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlumniRoute: typeof AuthenticatedAlumniRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevprofileRoute: typeof AuthenticatedDevprofileRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedHackathonsRoute: typeof AuthenticatedHackathonsRoute
  AuthenticatedInternshipsRoute: typeof AuthenticatedInternshipsRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedLinkedinOptimizerRoute: typeof AuthenticatedLinkedinOptimizerRoute
  AuthenticatedMentorRoute: typeof AuthenticatedMentorRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedStartupsRoute: typeof AuthenticatedStartupsRoute
  AuthenticatedRoomsSlugRoute: typeof AuthenticatedRoomsSlugRoute
  AuthenticatedRoomsIndexRoute: typeof AuthenticatedRoomsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlumniRoute: AuthenticatedAlumniRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevprofileRoute: AuthenticatedDevprofileRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedHackathonsRoute: AuthenticatedHackathonsRoute,
  AuthenticatedInternshipsRoute: AuthenticatedInternshipsRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedLinkedinOptimizerRoute: AuthenticatedLinkedinOptimizerRoute,
  AuthenticatedMentorRoute: AuthenticatedMentorRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedStartupsRoute: AuthenticatedStartupsRoute,
  AuthenticatedRoomsSlugRoute: AuthenticatedRoomsSlugRoute,
  AuthenticatedRoomsIndexRoute: AuthenticatedRoomsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DisclaimerRoute: DisclaimerRoute,
  FeaturesRoute: FeaturesRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminSumanRoute: AdminSumanRoute,
  BlogSlugRoute: BlogSlugRoute,
  UHandleRoute: UHandleRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAdminAgentChatRoute: ApiAdminAgentChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
